name = "stuproject"
compatibility_date = "2024-12-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "stuproject-db"
database_id = ""

# R2 and KV will be added when needed
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "stuproject-uploads"
#
# [[kv_namespaces]]
# binding = "KV"
# id = ""
