name = "stuproject"
main = "worker/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "stuproject-db"
database_id = "2cf25e07-cf29-4997-9cc4-c72bc4acf134"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "stuproject-uploads"

[ai]
binding = "AI"
